# UCM Configuration File Example
# 
# This file demonstrates how to configure UCM using YAML.
# You can use this config file by setting the path to this file in kv_connector_extra_config in launch script or command line like this:
# kv_connector_extra_config={"UCM_CONFIG_FILE": "/workspace/unified-cache-management/examples/ucm_config_example.yaml"}
#
# Alternatively, you can still use kv_connector_extra_config in KVTransferConfig
# for backward compatibility.

# Connector name (e.g., "UcmNfsStore", "UcmPipelineStore")
ucm_connectors:
  - ucm_connector_name: "UcmNfsStore"
    ucm_connector_config:
      storage_backends: "/home/zht/zht_3/test_data/ucm_data"
      io_direct: false

load_only_first_rank: false


record_config:
  enable: True
  log_path: "/home/zht/zht_3/unified-cache-management/ucm/store/test/e2e/temp/ucm_ops.log"
  flush_size: 10
  flush_interval: 5.0

# Enable UCM metrics so they can be monitored online via Grafana and Prometheus.
# metrics_config_path: "/workspace/unified-cache-management/examples/metrics/metrics_configs.yaml"

# Sparse attention configuration
# Format 1: Dictionary format (for methods like ESA, KvComp)
# ucm_sparse_config:
#   ESA:
#     init_window_sz: 1
#     local_window_sz: 2
#     min_blocks: 4
#     sparse_ratio: 0.3
#     retrieval_stride: 5
  # Or for GSA:
  # GSA: {}
  # Or for KvCompOnDevice:
  # GSA:
  #   "kvcompOnDevice_config_path": "workspace/unified-cache-management/ucm/sparse/kvcomp/configs/kvcomp_qwen3_32B_config.json"


# Whether to use layerwise loading/saving (optional, default: True for UCMConnector)
# use_layerwise: true
# hit_ratio: 0.9

